# Generated by Django 4.1 on 2022-08-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
                ('Image', models.ImageField(default='', upload_to='Product_Image/')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
